server:
  port: 8080
spring:
  application:
    name: "webhook"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/webhook
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'sa@123'
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  

